openapi: 3.0.4
info:
  title: Email Validator
  description: >-
    Email Validator is a simple tool for validating if an email address is valid
    or not. It checks the email address format and the domain records to see if
    the email address is valid.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/emailvalidator:
    get:
      summary: Validate Email
      description: Validate if an email address is valid and exists
      operationId: emailvalidator
      parameters:
        - name: email
          in: query
          schema:
            type: string
          required: true
          description: The email address to validate (e.g., support@myspace.com)
          example: support@myspace.com
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  creationDate: null
                  domain: myspace.com
                  email: support@myspace.com
                  username: support
                  canConnect: true
                  hasTypo: false
                  isValid: true
                  isMxValid: true
                  isSmtpValid: true
                  isRegexValid: true
                  smtp:
                    valid: true
                    reason: Connected
                  isCompanyEmail: true
                  isFreeEmail: false
                  checksum: 797
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
