name: apiverve_emailvalidator
description: Email Validator is a simple tool for validating if an email address is valid or not. It checks the email address format and the domain records to see if the email address is valid.
version: 1.1.14
homepage: https://emailvalidator.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/emailvalidator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
